



export const metadata = {
  title: 'Sign In | PopX',
  description: 'Generated by create next app',
}

export default function signinLayout({ children }) {
  return (
    <div className={`flex flex-col h-screen w-full bg-[#F7F8F9] p-[20px] `}>
      {children}
    </div>
  )
}
