

export const metadata = {
    title: 'Account Settings | PopX',
    description: 'Generated by create next app',
  }

export default function accountLayout ({children}){
    return(
        <div className="flex flex-col h-screen w-full bg-[#F7F8F9] " >{children}</div>
    )
}