export const metadata = {
  title: "Sign Up | PopX ",
  description: " Generated by Create next app",
};

export default function signupLayout({ children }) {
  return (
    <div className="flex flex-col h-screen bg-[#f7f8f9] p-[20px] ">
      {children}
    </div>
  );
}
